name: Locust CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy-locust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Authenticate to cluster
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Apply ConfigMap
        run: kubectl apply -f configmap.yaml -n item-core-sbx

      - name: Deploy Locust Master
        run: kubectl apply -f master.yaml -n item-core-sbx

      - name: Deploy Locust Workers
        run: kubectl apply -f worker.yaml -n item-core-sbx

      - name: Wait for Master Pod
        run: |
          kubectl rollout status deployment/perf-test-item-core-master -n item-core-sbx
          sleep 10

      - name: Trigger Locust Test (optional)
        run: |
          kubectl exec deploy/perf-test-item-core-master -n item-core-sbx -- \
          locust --headless -f /mnt/locust/load_test.py -u 100 -r 10 --run-time 5m --host https://your-target.com
