      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Test kubectl connection
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl version
          kubectl config get-contexts

      - name: Apply ConfigMap
        run: kubectl apply -f LoadTest_Sam.yaml -n item-core-sbx
